version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directories:
      - "/server-parquet"
      - "/druid-otlp-format"
    schedule:
      interval: "daily"
