name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: mishmash-io/github-workflows/.github/workflows/maven_build_with_provenance.yml@b4bbf8be1c9f467861d4a8ce2fe28bfaa715f933
    secrets: inherit
    with:
      java-version: 21

